export enum AstriaErrorCode {
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    NETWORK_ERROR = 'NETWORK_ERROR',
    TIMEOUT_ERROR = 'TIMEOUT_ERROR',

    AUTH_ERROR = 'AUTH_ERROR',

    API_ERROR = 'API_ERROR',
    RATE_LIMIT_ERROR = 'RATE_LIMIT_ERROR',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    VALIDATION_ERROR = 'VALIDATION_ERROR',

    SDK_ERROR = 'SDK_ERROR',
    POLLING_TIMEOUT = 'POLLING_TIMEOUT'
}
